# Build & deploy Python Flask Web App to Azure App Service — pa200-hw3-webapp
name: Deploy Flask WebApp - pa200-hw3-webapp

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # (volitelné) jednoduchá syntaktická kontrola
      - name: Lint
        run: python -m py_compile webapp/*.py

      # 📦 1) vytvoříme ZIP **uvnitř** složky webapp (bez vnořené podsložky)
      - name: Zip artifact for deployment
        run: |
          cd webapp
          zip -r ../webapp.zip .          # kořen ZIPu = app.py, requirements.txt, …

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-zip
          path: webapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-zip

      # 🚀 nasazení ZIPu přes publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pa200-hw3-webapp'                      # přesný název v Azure
          publish-profile: ${{ secrets.PHOTO_WEB_PUBLISH_PROFILE }}
          package: webapp.zip                               # ← ZIP s plochým kořenem
