name: Build and deploy Python Function App – func-resample

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # Oryx will treat this folder as “wwwroot”
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Validate Python syntax; Oryx will install dependencies at deploy-time.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Lint function code
        run: python -m py_compile function/**/*.py

      # ─── Zip exactly the CONTENTS of "function/" ───
      - name: Zip function folder contents
        run: |
          cd function
          zip -r ../function.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-zip
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-zip

      - name: Unzip artifact for deployment
        run: unzip function.zip   # produces a "./host.json", "./requirements.txt", "./resize/" etc.

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-resample'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  # points to "./function"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E06B36F647E3435DBA4A84AD08E4BD29 }}
